skip_commits:
  message: /^Merge pull request /

build: false

environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"

install:
  - call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - python --version
  - conda config --set always_yes yes
  - conda config --append channels pascallesage
  - conda update -y conda
  - conda install -y -c conda-forge -c cmutel xarray numpy pytest-cov coveralls bw2data wurst
  - pip install -e .

test_script:
  - pytest
