language: python
matrix:
  include:
    - language: generic
      python: 3.9
      os: osx
    - python: 3.9
      dist: xenial
      os: linux
python:
  - "3.9"
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      echo "Running on OS X";
      echo $(python3 --version);
      echo $(python --version);
    else
      echo "Running on Linux";
      sudo apt-get update;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda config --append channels conda-forge;
      conda config --append channels cmutel;
      conda config --append channels konstantinstadler;
      conda config --append channels haasad;
      conda config --append channels pascallesage;
      conda config --append channels romainsacchi;
      conda update conda;
      conda config --set channel_priority strict;
      conda info -a;
      echo $(python --version);
    fi
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      conda create -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pandas pytest pytest-cov
      coveralls xarray prettytable carculator carculator_truck pycountry bw2io bw2data wurst cryptography;
      source activate test-environment;
      pip3 install -e .;
      pip3 install pytest;
      pip3 install pytest-cov;
    else
      pip3 install -r ci/macos-travis.txt;
      pip3 install -e .;
    fi
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      pwd;
      ls;
      pytest -m "not ecoinvent" -s --cov=premise;
      coveralls;
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        conda install conda-build anaconda-client;
        bash ci/conda_upload.sh;
      fi
    else
      pytest -m "not ecoinvent" -s;
    fi
