language: python
matrix:
  include:
    - language: generic-covered
      python: 3.7
      os: osx
    - python: 3.7
      dist: xenial
      os: linux
python:
  - "3.7"
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      echo "Running on OS X";
      echo $(python3 --version);
      echo $(python --version);
    else
      echo "Running on Linux";
      sudo apt-get update;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda config --append channels conda-forge;
      conda config --append channels cmutel;
      conda update conda;
      conda info -a;
      echo $(python --version);
    fi
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      conda create -n test-environment python=$TRAVIS_PYTHON_VERSION numpy xarray pandas pytest pytest-cov coveralls brightway2 wurst;
      source activate test-environment;
      pip3 install -e .;
    else
      pip3 install -r ci/macos-travis.txt;
      pip3 install -e .;
    fi
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      pwd;
      ls;
      pytest --cov=rmnd-lca;
      coveralls;
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        conda install conda-build anaconda-client;
        bash ci/conda_upload.sh;
        
      fi
    else
      pytest;
    fi
